# Generated by Django 2.2.4 on 2019-08-08 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190807_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date published'),
        ),
    ]
