# Generated by Django 2.2.4 on 2019-08-08 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190808_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
