# Generated by Django 2.2.4 on 2019-08-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complete',
            new_name='Completed',
        ),
    ]
