# Generated by Django 2.2.4 on 2019-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20190808_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
