# Generated by Django 2.2.4 on 2019-08-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_todo_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='starred',
        ),
    ]
