# Generated by Django 2.2.4 on 2019-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_remove_todo_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
