# Generated by Django 2.2.4 on 2019-08-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_auto_20190810_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
