# Generated by Django 2.2.4 on 2019-08-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
