# Generated by Django 2.2.4 on 2019-08-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0017_auto_20190812_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
