# Generated by Django 2.2.4 on 2019-08-12 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0032_auto_20190812_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
