# Generated by Django 2.2.4 on 2019-08-12 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0033_auto_20190812_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='due date'),
        ),
    ]
